version: "3"
services:
  app_react:
    build: ./find-movie-front
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_node

  app_node:
    build: ./find-movie-back
    container_name: app_node
    ports:
      - 5000:5000
    volumes:
      - ./find-movie-back:/usr/src
      - /usr/src/node_modules
    command: "npm run start"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react: